# 붓꽃 종류 분류하기

In [49]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
from sklearn.datasets import load_iris
import pandas as pd
import os
import pickle

## 데이터 확인

각각의 속성은 cm 단위로 측정한 값
- 꽃받침 길이(sepal length)
- 너비(sepal width)
- 꽃잎 길이(petal length)
- 너비(petal width)

In [50]:
iris = load_iris()
iris.data[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

## 데이터 프레임으로 변환

In [51]:
iris_df = pd.DataFrame(iris.data, columns=iris.feature_names)
iris_df["target"] = pd.Series(iris.target)
iris_df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

## describe

In [52]:
iris_df.describe()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
count,150.000000,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333,1.000000
std,0.828066,0.435866,1.765298,0.762238,0.819232
min,4.300000,2.000000,1.000000,0.100000,0.000000
25%,5.100000,2.800000,1.600000,0.300000,0.000000
50%,5.800000,3.000000,4.350000,1.300000,1.000000
75%,6.400000,3.300000,5.100000,1.800000,2.000000
max,7.900000,4.400000,6.900000,2.500000,2.000000

## 라벨 확인

In [53]:
iris_df["target"].value_counts()

target
0    50
1    50
2    50
Name: count, dtype: int64

## 데이터, 라벨 준비

In [54]:
x = iris_df.iloc[:, :4]
y = iris_df.iloc[:, -1]

In [55]:
def iris_knn(x, y, k):
    train_data, test_data, train_label, test_label = train_test_split(x, y, test_size=0.3)
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(train_data, train_label)
    y_pred = knn.predict(test_data)
    return knn, metrics.accuracy_score(test_label, y_pred)

for k in range(1,31,5):
    model, scores = iris_knn(x, y, k)
    print(f"n_neighbors가 {k}일 때 정확도 : {scores:.3f}")

n_neighbors가 1일 때 정확도 : 0.911
n_neighbors가 6일 때 정확도 : 0.978
n_neighbors가 11일 때 정확도 : 0.978
n_neighbors가 16일 때 정확도 : 1.000
n_neighbors가 21일 때 정확도 : 0.978
n_neighbors가 26일 때 정확도 : 0.933

## 모델 저장

In [56]:
os.mkdir("model")
with open("model/iris_model.pkl", "wb") as f:
    pickle.dump(model, f)

print("모델 저장 완료")

모델 저장 완료

### k-nn의 단점  
- feature가 늘어날 수록 연산량이 늘어남